
// 
//  Font data for Franklin Gothic Medium Cond 8pt
//
//  Generated by The Dot Factory:
//  http://www.eran.io/the-dot-factory-an-lcd-font-and-image-generator/
// 
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
// Dot Factory Settings
// 
// Flip/Rotate      Padding Removal           Line Wrap         Descriptors
//   [X] Flip X       Height(Y): None           (O) At column     [X] Generate descriptor array
//   [ ] Flip Y       Width(X):  Tightest       ( ) At bitmap       Char Width:  In Bits
//       90deg                                                      Char Height: In Bits
//                                                                  Font Height: In Bits
// Comments                  Byte                                     [ ] Multiple descriptor arrays
//   [X] Variable Name         Bit layout: RowMajor                   
//   [X] BMP visualise   [#]   Order:      MSBfirst                 Create new when exceeds [80]
//   [X] Char descriptor       Format:     Hex                        
//    Style: Cpp               Leading:    0x                       Image width:  In Bits
//                                                                  Image height: In Bits
//  Variable name format                                          
//    Bitmaps:   const uint8_t PROGMEM {0}Bitmaps               Space char generation
//    Char Info: const FONT_CHAR_INFO PROGMEM {0}Descriptors      [ ] Generate space bitmap
//    Font Info: const FONT_INFO {0}FontInfo                      [2] pixels for space char     
//    Width:     const uint8_t {0}Width                           
//    Height:    const uint8_t {0}Height
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "FranklinGothic.h"

// Character bitmaps for Franklin Gothic Medium Cond 8pt
const uint8_t PROGMEM franklinGothicMediumCond_8ptBitmaps [] = 
{
	// @0 ' ' (2 pixels wide)
	0x00, 0x00, //                
	0x00, 0x00, //                

	// @4 '!' (1 pixels wide)
	0x0F, 0xD0, //     ###### #   

	// @6 '"' (3 pixels wide)
	0x0E, 0x00, //     ###        
	0x00, 0x00, //                
	0x0E, 0x00, //     ###        

	// @12 '#' (6 pixels wide)
	0x02, 0x40, //       #  #     
	0x0F, 0xF0, //     ########   
	0x02, 0x40, //       #  #     
	0x02, 0x40, //       #  #     
	0x0F, 0xF0, //     ########   
	0x02, 0x40, //       #  #     

	// @24 '$' (5 pixels wide)
	0x03, 0x20, //       ##  #    
	0x04, 0x90, //      #  #  #   
	0x0F, 0xF8, //     #########  
	0x04, 0x90, //      #  #  #   
	0x02, 0x60, //       #  ##    

	// @34 '%' (7 pixels wide)
	0x06, 0x00, //      ##        
	0x09, 0x10, //     #  #   #   
	0x06, 0x60, //      ##  ##    
	0x01, 0x80, //        ##      
	0x06, 0x60, //      ##  ##    
	0x08, 0x90, //     #   #  #   
	0x00, 0x60, //          ##    

	// @48 '&' (6 pixels wide)
	0x00, 0x60, //          ##    
	0x06, 0x90, //      ## #  #   
	0x09, 0x90, //     #  ##  #   
	0x09, 0x50, //     #  # # #   
	0x06, 0x20, //      ##   #    
	0x00, 0xD0, //         ## #   

	// @60 ''' (1 pixels wide)
	0x0E, 0x00, //     ###        

	// @62 '(' (2 pixels wide)
	0x07, 0xF8, //      ########  
	0x08, 0x04, //     #        # 

	// @66 ')' (2 pixels wide)
	0x08, 0x04, //     #        # 
	0x07, 0xF8, //      ########  

	// @70 '*' (3 pixels wide)
	0x06, 0x00, //      ##        
	0x0F, 0x00, //     ####       
	0x06, 0x00, //      ##        

	// @76 '+' (5 pixels wide)
	0x00, 0x80, //         #      
	0x00, 0x80, //         #      
	0x03, 0xE0, //       #####    
	0x00, 0x80, //         #      
	0x00, 0x80, //         #      

	// @86 ',' (1 pixels wide)
	0x00, 0x1C, //            ### 

	// @88 '-' (2 pixels wide)
	0x00, 0x40, //          #     
	0x00, 0x40, //          #     

	// @92 '.' (1 pixels wide)
	0x00, 0x10, //            #   

	// @94 '/' (5 pixels wide)
	0x00, 0x04, //              # 
	0x00, 0x38, //           ###  
	0x00, 0xC0, //         ##     
	0x07, 0x00, //      ###       
	0x08, 0x00, //     #          

	// @104 '0' (5 pixels wide)
	0x07, 0xE0, //      ######    
	0x08, 0x10, //     #      #   
	0x08, 0x10, //     #      #   
	0x08, 0x10, //     #      #   
	0x07, 0xE0, //      ######    

	// @114 '1' (3 pixels wide)
	0x04, 0x10, //      #     #   
	0x0F, 0xF0, //     ########   
	0x00, 0x10, //            #   

	// @120 '2' (5 pixels wide)
	0x04, 0x10, //      #     #   
	0x08, 0x30, //     #     ##   
	0x08, 0x50, //     #    # #   
	0x08, 0x90, //     #   #  #   
	0x07, 0x10, //      ###   #   

	// @130 '3' (5 pixels wide)
	0x04, 0x20, //      #    #    
	0x08, 0x10, //     #      #   
	0x09, 0x10, //     #  #   #   
	0x09, 0x10, //     #  #   #   
	0x06, 0xE0, //      ## ###    

	// @140 '4' (6 pixels wide)
	0x00, 0xC0, //         ##     
	0x01, 0x40, //        # #     
	0x02, 0x40, //       #  #     
	0x04, 0x40, //      #   #     
	0x0F, 0xF0, //     ########   
	0x00, 0x40, //          #     

	// @152 '5' (5 pixels wide)
	0x0F, 0xA0, //     ##### #    
	0x09, 0x10, //     #  #   #   
	0x09, 0x10, //     #  #   #   
	0x09, 0x10, //     #  #   #   
	0x08, 0xE0, //     #   ###    

	// @162 '6' (5 pixels wide)
	0x07, 0xE0, //      ######    
	0x09, 0x10, //     #  #   #   
	0x09, 0x10, //     #  #   #   
	0x09, 0x10, //     #  #   #   
	0x04, 0xE0, //      #  ###    

	// @172 '7' (5 pixels wide)
	0x08, 0x00, //     #          
	0x08, 0x00, //     #          
	0x08, 0xF0, //     #   ####   
	0x0B, 0x00, //     # ##       
	0x0C, 0x00, //     ##         

	// @182 '8' (5 pixels wide)
	0x06, 0xE0, //      ## ###    
	0x09, 0x10, //     #  #   #   
	0x09, 0x10, //     #  #   #   
	0x09, 0x10, //     #  #   #   
	0x06, 0xE0, //      ## ###    

	// @192 '9' (5 pixels wide)
	0x07, 0x20, //      ###  #    
	0x08, 0x90, //     #   #  #   
	0x08, 0x90, //     #   #  #   
	0x08, 0x90, //     #   #  #   
	0x07, 0xE0, //      ######    

	// @202 ':' (1 pixels wide)
	0x02, 0x10, //       #    #   

	// @204 ';' (1 pixels wide)
	0x02, 0x1C, //       #    ### 

	// @206 '<' (5 pixels wide)
	0x01, 0x80, //        ##      
	0x01, 0x80, //        ##      
	0x02, 0x40, //       #  #     
	0x02, 0x40, //       #  #     
	0x04, 0x20, //      #    #    

	// @216 '=' (4 pixels wide)
	0x01, 0x40, //        # #     
	0x01, 0x40, //        # #     
	0x01, 0x40, //        # #     
	0x01, 0x40, //        # #     

	// @224 '>' (5 pixels wide)
	0x04, 0x20, //      #    #    
	0x02, 0x40, //       #  #     
	0x02, 0x40, //       #  #     
	0x01, 0x80, //        ##      
	0x01, 0x80, //        ##      

	// @234 '?' (4 pixels wide)
	0x06, 0x00, //      ##        
	0x08, 0xD0, //     #   ## #   
	0x09, 0x00, //     #  #       
	0x06, 0x00, //      ##        

	// @242 '@' (7 pixels wide)
	0x03, 0xC0, //       ####     
	0x04, 0x20, //      #    #    
	0x09, 0x90, //     #  ##  #   
	0x0A, 0x50, //     # #  # #   
	0x0B, 0x90, //     # ###  #   
	0x08, 0x40, //     #    #     
	0x07, 0x80, //      ####      

	// @256 'A' (5 pixels wide)
	0x00, 0x70, //          ###   
	0x03, 0xC0, //       ####     
	0x0C, 0x40, //     ##   #     
	0x03, 0xC0, //       ####     
	0x00, 0x70, //          ###   

	// @266 'B' (5 pixels wide)
	0x0F, 0xF0, //     ########   
	0x09, 0x10, //     #  #   #   
	0x09, 0x10, //     #  #   #   
	0x09, 0x10, //     #  #   #   
	0x06, 0xE0, //      ## ###    

	// @276 'C' (5 pixels wide)
	0x07, 0xE0, //      ######    
	0x08, 0x10, //     #      #   
	0x08, 0x10, //     #      #   
	0x08, 0x10, //     #      #   
	0x06, 0x60, //      ##  ##    

	// @286 'D' (5 pixels wide)
	0x0F, 0xF0, //     ########   
	0x08, 0x10, //     #      #   
	0x08, 0x10, //     #      #   
	0x04, 0x20, //      #    #    
	0x03, 0xC0, //       ####     

	// @296 'E' (4 pixels wide)
	0x0F, 0xF0, //     ########   
	0x09, 0x10, //     #  #   #   
	0x09, 0x10, //     #  #   #   
	0x08, 0x10, //     #      #   

	// @304 'F' (4 pixels wide)
	0x0F, 0xF0, //     ########   
	0x09, 0x00, //     #  #       
	0x09, 0x00, //     #  #       
	0x08, 0x00, //     #          

	// @312 'G' (5 pixels wide)
	0x07, 0xE0, //      ######    
	0x08, 0x10, //     #      #   
	0x08, 0x10, //     #      #   
	0x08, 0x90, //     #   #  #   
	0x06, 0xF0, //      ## ####   

	// @322 'H' (5 pixels wide)
	0x0F, 0xF0, //     ########   
	0x01, 0x00, //        #       
	0x01, 0x00, //        #       
	0x01, 0x00, //        #       
	0x0F, 0xF0, //     ########   

	// @332 'I' (1 pixels wide)
	0x0F, 0xF0, //     ########   

	// @334 'J' (2 pixels wide)
	0x00, 0x10, //            #   
	0x0F, 0xF0, //     ########   

	// @338 'K' (5 pixels wide)
	0x0F, 0xF0, //     ########   
	0x01, 0x00, //        #       
	0x03, 0x80, //       ###      
	0x04, 0x60, //      #   ##    
	0x08, 0x10, //     #      #   

	// @348 'L' (4 pixels wide)
	0x0F, 0xF0, //     ########   
	0x00, 0x10, //            #   
	0x00, 0x10, //            #   
	0x00, 0x10, //            #   

	// @356 'M' (7 pixels wide)
	0x0F, 0xF0, //     ########   
	0x0C, 0x00, //     ##         
	0x03, 0xC0, //       ####     
	0x00, 0x30, //           ##   
	0x03, 0xC0, //       ####     
	0x0C, 0x00, //     ##         
	0x0F, 0xF0, //     ########   

	// @370 'N' (5 pixels wide)
	0x0F, 0xF0, //     ########   
	0x06, 0x00, //      ##        
	0x01, 0x80, //        ##      
	0x00, 0x60, //          ##    
	0x0F, 0xF0, //     ########   

	// @380 'O' (5 pixels wide)
	0x07, 0xE0, //      ######    
	0x08, 0x10, //     #      #   
	0x08, 0x10, //     #      #   
	0x08, 0x10, //     #      #   
	0x07, 0xE0, //      ######    

	// @390 'P' (4 pixels wide)
	0x0F, 0xF0, //     ########   
	0x08, 0x80, //     #   #      
	0x08, 0x80, //     #   #      
	0x07, 0x00, //      ###       

	// @398 'Q' (5 pixels wide)
	0x07, 0xE0, //      ######    
	0x08, 0x10, //     #      #   
	0x08, 0x18, //     #      ##  
	0x08, 0x14, //     #      # # 
	0x07, 0xE4, //      ######  # 

	// @408 'R' (5 pixels wide)
	0x0F, 0xF0, //     ########   
	0x08, 0x80, //     #   #      
	0x08, 0xC0, //     #   ##     
	0x08, 0xA0, //     #   # #    
	0x07, 0x10, //      ###   #   

	// @418 'S' (5 pixels wide)
	0x06, 0x20, //      ##   #    
	0x09, 0x10, //     #  #   #   
	0x09, 0x10, //     #  #   #   
	0x08, 0x90, //     #   #  #   
	0x04, 0x60, //      #   ##    

	// @428 'T' (5 pixels wide)
	0x08, 0x00, //     #          
	0x08, 0x00, //     #          
	0x0F, 0xF0, //     ########   
	0x08, 0x00, //     #          
	0x08, 0x00, //     #          

	// @438 'U' (5 pixels wide)
	0x0F, 0xE0, //     #######    
	0x00, 0x10, //            #   
	0x00, 0x10, //            #   
	0x00, 0x10, //            #   
	0x0F, 0xE0, //     #######    

	// @448 'V' (5 pixels wide)
	0x0C, 0x00, //     ##         
	0x03, 0xE0, //       #####    
	0x00, 0x10, //            #   
	0x03, 0xE0, //       #####    
	0x0C, 0x00, //     ##         

	// @458 'W' (7 pixels wide)
	0x0F, 0x80, //     #####      
	0x00, 0x70, //          ###   
	0x03, 0x80, //       ###      
	0x0C, 0x00, //     ##         
	0x03, 0xC0, //       ####     
	0x00, 0x70, //          ###   
	0x0F, 0x80, //     #####      

	// @472 'X' (5 pixels wide)
	0x08, 0x10, //     #      #   
	0x06, 0x60, //      ##  ##    
	0x01, 0x80, //        ##      
	0x06, 0x60, //      ##  ##    
	0x08, 0x10, //     #      #   

	// @482 'Y' (5 pixels wide)
	0x08, 0x00, //     #          
	0x06, 0x00, //      ##        
	0x01, 0xF0, //        #####   
	0x06, 0x00, //      ##        
	0x08, 0x00, //     #          

	// @492 'Z' (4 pixels wide)
	0x08, 0x30, //     #     ##   
	0x08, 0xD0, //     #   ## #   
	0x0B, 0x10, //     # ##   #   
	0x0C, 0x10, //     ##     #   

	// @500 '[' (2 pixels wide)
	0x0F, 0xFC, //     ########## 
	0x08, 0x04, //     #        # 

	// @504 '\' (4 pixels wide)
	0x04, 0x00, //      #         
	0x03, 0x80, //       ###      
	0x00, 0x70, //          ###   
	0x00, 0x0C, //             ## 

	// @512 ']' (2 pixels wide)
	0x08, 0x04, //     #        # 
	0x0F, 0xFC, //     ########## 

	// @516 '^' (5 pixels wide)
	0x00, 0x80, //         #      
	0x03, 0x00, //       ##       
	0x04, 0x00, //      #         
	0x03, 0x00, //       ##       
	0x00, 0x80, //         #      

	// @526 '_' (6 pixels wide)
	0x00, 0x04, //              # 
	0x00, 0x04, //              # 
	0x00, 0x04, //              # 
	0x00, 0x04, //              # 
	0x00, 0x04, //              # 
	0x00, 0x04, //              # 

	// @538 '`' (2 pixels wide)
	0x10, 0x00, //    #           
	0x08, 0x00, //     #          

	// @542 'a' (4 pixels wide)
	0x00, 0x60, //          ##    
	0x02, 0x90, //       # #  #   
	0x02, 0x90, //       # #  #   
	0x01, 0xF0, //        #####   

	// @550 'b' (4 pixels wide)
	0x0F, 0xF0, //     ########   
	0x02, 0x10, //       #    #   
	0x02, 0x10, //       #    #   
	0x01, 0xE0, //        ####    

	// @558 'c' (4 pixels wide)
	0x01, 0xE0, //        ####    
	0x02, 0x10, //       #    #   
	0x02, 0x10, //       #    #   
	0x01, 0x20, //        #  #    

	// @566 'd' (4 pixels wide)
	0x01, 0xE0, //        ####    
	0x02, 0x10, //       #    #   
	0x02, 0x10, //       #    #   
	0x0F, 0xF0, //     ########   

	// @574 'e' (4 pixels wide)
	0x01, 0xE0, //        ####    
	0x02, 0x90, //       # #  #   
	0x02, 0x90, //       # #  #   
	0x01, 0xA0, //        ## #    

	// @582 'f' (3 pixels wide)
	0x02, 0x00, //       #        
	0x07, 0xF0, //      #######   
	0x0A, 0x00, //     # #        

	// @588 'g' (5 pixels wide)
	0x01, 0xA8, //        ## # #  
	0x02, 0x54, //       #  # # # 
	0x02, 0x54, //       #  # # # 
	0x03, 0x94, //       ###  # # 
	0x04, 0x08, //      #      #  

	// @598 'h' (4 pixels wide)
	0x0F, 0xF0, //     ########   
	0x02, 0x00, //       #        
	0x02, 0x00, //       #        
	0x01, 0xF0, //        #####   

	// @606 'i' (1 pixels wide)
	0x0B, 0xF0, //     # ######   

	// @608 'j' (2 pixels wide)
	0x00, 0x04, //              # 
	0x0B, 0xFC, //     # ######## 

	// @612 'k' (4 pixels wide)
	0x0F, 0xF0, //     ########   
	0x00, 0x80, //         #      
	0x01, 0x60, //        # ##    
	0x02, 0x10, //       #    #   

	// @620 'l' (1 pixels wide)
	0x0F, 0xF0, //     ########   

	// @622 'm' (7 pixels wide)
	0x03, 0xF0, //       ######   
	0x02, 0x00, //       #        
	0x02, 0x00, //       #        
	0x01, 0xF0, //        #####   
	0x02, 0x00, //       #        
	0x02, 0x00, //       #        
	0x01, 0xF0, //        #####   

	// @636 'n' (4 pixels wide)
	0x03, 0xF0, //       ######   
	0x02, 0x00, //       #        
	0x02, 0x00, //       #        
	0x01, 0xF0, //        #####   

	// @644 'o' (4 pixels wide)
	0x01, 0xE0, //        ####    
	0x02, 0x10, //       #    #   
	0x02, 0x10, //       #    #   
	0x01, 0xE0, //        ####    

	// @652 'p' (4 pixels wide)
	0x03, 0xFC, //       ######## 
	0x02, 0x10, //       #    #   
	0x02, 0x10, //       #    #   
	0x01, 0xE0, //        ####    

	// @660 'q' (4 pixels wide)
	0x01, 0xE0, //        ####    
	0x02, 0x10, //       #    #   
	0x02, 0x10, //       #    #   
	0x03, 0xFC, //       ######## 

	// @668 'r' (3 pixels wide)
	0x03, 0xF0, //       ######   
	0x01, 0x00, //        #       
	0x02, 0x00, //       #        

	// @674 's' (3 pixels wide)
	0x01, 0x10, //        #   #   
	0x02, 0x90, //       # #  #   
	0x02, 0x60, //       #  ##    

	// @680 't' (3 pixels wide)
	0x02, 0x00, //       #        
	0x0F, 0xF0, //     ########   
	0x02, 0x10, //       #    #   

	// @686 'u' (4 pixels wide)
	0x03, 0xE0, //       #####    
	0x00, 0x10, //            #   
	0x00, 0x20, //           #    
	0x03, 0xF0, //       ######   

	// @694 'v' (5 pixels wide)
	0x02, 0x00, //       #        
	0x01, 0xC0, //        ###     
	0x00, 0x30, //           ##   
	0x01, 0xC0, //        ###     
	0x02, 0x00, //       #        

	// @704 'w' (5 pixels wide)
	0x03, 0xC0, //       ####     
	0x00, 0x30, //           ##   
	0x03, 0xC0, //       ####     
	0x00, 0x30, //           ##   
	0x03, 0xC0, //       ####     

	// @714 'x' (3 pixels wide)
	0x03, 0x30, //       ##  ##   
	0x00, 0xC0, //         ##     
	0x03, 0x30, //       ##  ##   

	// @720 'y' (3 pixels wide)
	0x03, 0xC4, //       ####   # 
	0x00, 0x38, //           ###  
	0x03, 0xC0, //       ####     

	// @726 'z' (3 pixels wide)
	0x02, 0x30, //       #   ##   
	0x02, 0xD0, //       # ## #   
	0x03, 0x10, //       ##   #   

	// @732 '{' (3 pixels wide)
	0x00, 0x40, //          #     
	0x0F, 0xBC, //     ##### #### 
	0x08, 0x04, //     #        # 

	// @738 '|' (1 pixels wide)
	0x0F, 0xFC, //     ########## 

	// @740 '}' (3 pixels wide)
	0x08, 0x04, //     #        # 
	0x0F, 0xBC, //     ##### #### 
	0x00, 0x40, //          #     

	// @746 '~' (5 pixels wide)
	0x00, 0x40, //          #     
	0x00, 0x80, //         #      
	0x00, 0xC0, //         ##     
	0x00, 0x40, //          #     
	0x00, 0x80, //         #      
};

// Character descriptors for Franklin Gothic Medium Cond 8pt
// { [Char width in bits], [Char height in bits], [Offset into franklinGothicMediumCond_8ptCharBitmaps in bytes] }
const FONT_CHAR_INFO PROGMEM franklinGothicMediumCond_8ptDescriptors[] = 
{
	{2, 15, 0}, 		//   
	{1, 15, 4}, 		// ! 
	{3, 15, 6}, 		// " 
	{6, 15, 12}, 		// # 
	{5, 15, 24}, 		// $ 
	{7, 15, 34}, 		// % 
	{6, 15, 48}, 		// & 
	{1, 15, 60}, 		// ' 
	{2, 15, 62}, 		// ( 
	{2, 15, 66}, 		// ) 
	{3, 15, 70}, 		// * 
	{5, 15, 76}, 		// + 
	{1, 15, 86}, 		// , 
	{2, 15, 88}, 		// - 
	{1, 15, 92}, 		// . 
	{5, 15, 94}, 		// / 
	{5, 15, 104}, 		// 0 
	{3, 15, 114}, 		// 1 
	{5, 15, 120}, 		// 2 
	{5, 15, 130}, 		// 3 
	{6, 15, 140}, 		// 4 
	{5, 15, 152}, 		// 5 
	{5, 15, 162}, 		// 6 
	{5, 15, 172}, 		// 7 
	{5, 15, 182}, 		// 8 
	{5, 15, 192}, 		// 9 
	{1, 15, 202}, 		// : 
	{1, 15, 204}, 		// ; 
	{5, 15, 206}, 		// < 
	{4, 15, 216}, 		// = 
	{5, 15, 224}, 		// > 
	{4, 15, 234}, 		// ? 
	{7, 15, 242}, 		// @ 
	{5, 15, 256}, 		// A 
	{5, 15, 266}, 		// B 
	{5, 15, 276}, 		// C 
	{5, 15, 286}, 		// D 
	{4, 15, 296}, 		// E 
	{4, 15, 304}, 		// F 
	{5, 15, 312}, 		// G 
	{5, 15, 322}, 		// H 
	{1, 15, 332}, 		// I 
	{2, 15, 334}, 		// J 
	{5, 15, 338}, 		// K 
	{4, 15, 348}, 		// L 
	{7, 15, 356}, 		// M 
	{5, 15, 370}, 		// N 
	{5, 15, 380}, 		// O 
	{4, 15, 390}, 		// P 
	{5, 15, 398}, 		// Q 
	{5, 15, 408}, 		// R 
	{5, 15, 418}, 		// S 
	{5, 15, 428}, 		// T 
	{5, 15, 438}, 		// U 
	{5, 15, 448}, 		// V 
	{7, 15, 458}, 		// W 
	{5, 15, 472}, 		// X 
	{5, 15, 482}, 		// Y 
	{4, 15, 492}, 		// Z 
	{2, 15, 500}, 		// [ 
	{4, 15, 504}, 		// \ .
	{2, 15, 512}, 		// ] 
	{5, 15, 516}, 		// ^ 
	{6, 15, 526}, 		// _ 
	{2, 15, 538}, 		// ` 
	{4, 15, 542}, 		// a 
	{4, 15, 550}, 		// b 
	{4, 15, 558}, 		// c 
	{4, 15, 566}, 		// d 
	{4, 15, 574}, 		// e 
	{3, 15, 582}, 		// f 
	{5, 15, 588}, 		// g 
	{4, 15, 598}, 		// h 
	{1, 15, 606}, 		// i 
	{2, 15, 608}, 		// j 
	{4, 15, 612}, 		// k 
	{1, 15, 620}, 		// l 
	{7, 15, 622}, 		// m 
	{4, 15, 636}, 		// n 
	{4, 15, 644}, 		// o 
	{4, 15, 652}, 		// p 
	{4, 15, 660}, 		// q 
	{3, 15, 668}, 		// r 
	{3, 15, 674}, 		// s 
	{3, 15, 680}, 		// t 
	{4, 15, 686}, 		// u 
	{5, 15, 694}, 		// v 
	{5, 15, 704}, 		// w 
	{3, 15, 714}, 		// x 
	{3, 15, 720}, 		// y 
	{3, 15, 726}, 		// z 
	{3, 15, 732}, 		// { 
	{1, 15, 738}, 		// | 
	{3, 15, 740}, 		// } 
	{5, 15, 746}, 		// ~ 
};


// Font information for Franklin Gothic Medium Cond 8pt
const FONT_INFO franklinGothicMediumCond_8ptFontInfo =
{
	15, //  Character height
	' ', //  Start character
	'z', //  End character
	1, //  Width, in pixels, of space character
	franklinGothicMediumCond_8ptDescriptors, //  Character descriptor array
	franklinGothicMediumCond_8ptBitmaps, //  Character bitmap array
};

// 
//  Font data for Franklin Gothic Medium Cond 7pt
// 

// Character bitmaps for Franklin Gothic Medium Cond 7pt
const uint8_t PROGMEM franklinGothicMediumCond_7ptBitmaps [] = 
{
	// @0 ' ' (2 pixels wide)
	0x00, 0x00, //             
	0x00, 0x00, //             

	// @4 ',' (1 pixels wide)
	0xC0, // ##

	// @5 '.' (1 pixels wide)
	0x80, // #

	// @6 '/' (4 pixels wide)
	0x01, //        #
	0x0E, //     ### 
	0x70, //  ###    
	0x80, // #       

	// @10 '0' (4 pixels wide)
	0x78, //  #### 
	0x84, // #    #
	0x84, // #    #
	0x78, //  #### 

	// @14 '1' (3 pixels wide)
	0x44, //  #   #
	0xFC, // ######
	0x04, //      #

	// @17 '2' (4 pixels wide)
	0x44, //  #   #
	0x8C, // #   ##
	0x94, // #  # #
	0x64, //  ##  #

	// @21 '3' (4 pixels wide)
	0x48, //  #  # 
	0x84, // #    #
	0xA4, // # #  #
	0x58, //  # ## 

	// @25 '4' (5 pixels wide)
	0x18, //    ## 
	0x68, //  ## # 
	0x88, // #   # 
	0xFC, // ######
	0x08, //     # 

	// @30 '5' (4 pixels wide)
	0xE8, // ### # 
	0xA4, // # #  #
	0xA4, // # #  #
	0x98, // #  ## 

	// @34 '6' (4 pixels wide)
	0x78, //  #### 
	0xA4, // # #  #
	0xA4, // # #  #
	0x18, //    ## 

	// @38 '7' (4 pixels wide)
	0x80, // #     
	0x9C, // #  ###
	0xA0, // # #   
	0xC0, // ##    

	// @42 '8' (4 pixels wide)
	0x58, //  # ## 
	0xA4, // # #  #
	0xA4, // # #  #
	0x58, //  # ## 

	// @46 '9' (4 pixels wide)
	0x60, //  ##   
	0x94, // #  # #
	0x94, // #  # #
	0x78, //  #### 

	// @50 ':' (1 pixels wide)
	0x88, // #   #

	// @51 'A' (3 pixels wide)
	0x3C, //   ####
	0xC8, // ##  # 
	0x3C, //   ####

	// @54 'B' (4 pixels wide)
	0xFC, // ######
	0xA4, // # #  #
	0xA4, // # #  #
	0x58, //  # ## 

	// @58 'C' (4 pixels wide)
	0x78, //  #### 
	0x84, // #    #
	0x84, // #    #
	0x48, //  #  # 

	// @62 'D' (4 pixels wide)
	0xFC, // ######
	0x84, // #    #
	0x84, // #    #
	0x78, //  #### 

	// @66 'E' (3 pixels wide)
	0xFC, // ######
	0xA4, // # #  #
	0xA4, // # #  #

	// @69 'F' (3 pixels wide)
	0xFC, // ######
	0x90, // #  #  
	0x90, // #  #  

	// @72 'G' (4 pixels wide)
	0x78, //  #### 
	0x84, // #    #
	0x94, // #  # #
	0x5C, //  # ###

	// @76 'H' (4 pixels wide)
	0xFC, // ######
	0x20, //   #   
	0x20, //   #   
	0xFC, // ######

	// @80 'I' (1 pixels wide)
	0xFC, // ######

	// @81 'J' (2 pixels wide)
	0x04, //      #
	0xFC, // ######

	// @83 'K' (4 pixels wide)
	0xFC, // ######
	0x20, //   #   
	0x58, //  # ## 
	0x84, // #    #

	// @87 'L' (3 pixels wide)
	0xFC, // ######
	0x04, //      #
	0x04, //      #

	// @90 'M' (5 pixels wide)
	0xFC, // ######
	0x60, //  ##   
	0x1C, //    ###
	0x60, //  ##   
	0xFC, // ######

	// @95 'N' (4 pixels wide)
	0xFC, // ######
	0x60, //  ##   
	0x18, //    ## 
	0xFC, // ######

	// @99 'O' (4 pixels wide)
	0x78, //  #### 
	0x84, // #    #
	0x84, // #    #
	0x78, //  #### 

	// @103 'P' (3 pixels wide)
	0xFC, // ######
	0x90, // #  #  
	0x60, //  ##   

	// @106 'Q' (4 pixels wide)
	0x78, //  ####  
	0x84, // #    # 
	0x86, // #    ##
	0x7A, //  #### #

	// @110 'R' (4 pixels wide)
	0xFC, // ######
	0x90, // #  #  
	0x98, // #  ## 
	0x64, //  ##  #

	// @114 'S' (4 pixels wide)
	0x48, //  #  # 
	0xA4, // # #  #
	0x94, // #  # #
	0x48, //  #  # 

	// @118 'T' (3 pixels wide)
	0x80, // #     
	0xFC, // ######
	0x80, // #     

	// @121 'U' (4 pixels wide)
	0xF8, // ##### 
	0x04, //      #
	0x04, //      #
	0xF8, // ##### 

	// @125 'V' (3 pixels wide)
	0xF0, // ####  
	0x0C, //     ##
	0xF0, // ####  

	// @128 'W' (5 pixels wide)
	0xF0, // ####  
	0x0C, //     ##
	0xF0, // ####  
	0x0C, //     ##
	0xF0, // ####  

	// @133 'X' (3 pixels wide)
	0xCC, // ##  ##
	0x30, //   ##  
	0xCC, // ##  ##

	// @136 'Y' (5 pixels wide)
	0x80, // #     
	0x60, //  ##   
	0x1C, //    ###
	0x60, //  ##   
	0x80, // #     

	// @141 'Z' (3 pixels wide)
	0x8C, // #   ##
	0xB4, // # ## #
	0xC4, // ##   #

	// @144 '\' (4 pixels wide)
	0x80, // #       
	0x70, //  ###    
	0x0C, //     ##  
	0x03, //       ##

	// @148 '`' (2 pixels wide)
	0x80, // # 
	0x40, //  #

	// @150 'a' (3 pixels wide)
	0x90, // #  # 
	0xA8, // # # #
	0x78, //  ####

	// @153 'b' (3 pixels wide)
	0xFC, // ######
	0x44, //  #   #
	0x38, //   ### 

	// @156 'c' (3 pixels wide)
	0x70, //  ### 
	0x88, // #   #
	0x50, //  # # 

	// @159 'd' (3 pixels wide)
	0x38, //   ### 
	0x44, //  #   #
	0xFC, // ######

	// @162 'e' (3 pixels wide)
	0x70, //  ### 
	0xA8, // # # #
	0x68, //  ## #

	// @165 'f' (2 pixels wide)
	0x7C, //  #####
	0xA0, // # #   

	// @167 'g' (4 pixels wide)
	0x2A, //   # # # 
	0x55, //  # # # #
	0x65, //  ##  # #
	0x82, // #     # 

	// @171 'h' (3 pixels wide)
	0xFC, // ######
	0x40, //  #    
	0x3C, //   ####

	// @174 'i' (1 pixels wide)
	0xBE, // # #####

	// @175 'j' (2 pixels wide)
	0x00, 0x80, //         #
	0xBF, 0x80, // # #######

	// @179 'k' (3 pixels wide)
	0xFC, // ######
	0x30, //   ##  
	0x4C, //  #  ##

	// @182 'l' (1 pixels wide)
	0xFC, // ######

	// @183 'm' (5 pixels wide)
	0xF8, // #####
	0x80, // #    
	0xF8, // #####
	0x80, // #    
	0x78, //  ####

	// @188 'n' (3 pixels wide)
	0xF8, // #####
	0x80, // #    
	0x78, //  ####

	// @191 'o' (3 pixels wide)
	0x70, //  ### 
	0x88, // #   #
	0x70, //  ### 

	// @194 'p' (3 pixels wide)
	0xFE, // #######
	0x88, // #   #  
	0x70, //  ###   

	// @197 'q' (3 pixels wide)
	0x70, //  ###   
	0x88, // #   #  
	0xFE, // #######

	// @200 'r' (3 pixels wide)
	0xF8, // #####
	0x40, //  #   
	0x80, // #    

	// @203 's' (3 pixels wide)
	0x48, //  #  #
	0xA8, // # # #
	0x90, // #  # 

	// @206 't' (2 pixels wide)
	0xFC, // ######
	0x44, //  #   #

	// @208 'u' (3 pixels wide)
	0xF0, // #### 
	0x08, //     #
	0xF8, // #####

	// @211 'v' (3 pixels wide)
	0xE0, // ###  
	0x18, //    ##
	0xE0, // ###  

	// @214 'w' (5 pixels wide)
	0xE0, // ###  
	0x18, //    ##
	0xE0, // ###  
	0x18, //    ##
	0xE0, // ###  

	// @219 'x' (3 pixels wide)
	0x88, // #   #
	0x70, //  ### 
	0x88, // #   #

	// @222 'y' (3 pixels wide)
	0xE2, // ###   #
	0x1C, //    ### 
	0xE0, // ###    

	// @225 'z' (2 pixels wide)
	0xB8, // # ###
	0xC8, // ##  #
};

// Character descriptors for Franklin Gothic Medium Cond 7pt
// { [Char width in bits], [Char height in bits], [Offset into franklinGothicMediumCond_7ptCharBitmaps in bytes] }
const FONT_CHAR_INFO PROGMEM franklinGothicMediumCond_7ptDescriptors[] = 
{
	{1, 7, 0}, 		//   
	{0, 0, 0}, 		// ! 
	{0, 0, 0}, 		// " 
	{0, 0, 0}, 		// # 
	{0, 0, 0}, 		// $ 
	{0, 0, 0}, 		// % 
	{0, 0, 0}, 		// & 
	{0, 0, 0}, 		// ' 
	{0, 0, 0}, 		// ( 
	{0, 0, 0}, 		// ) 
	{0, 0, 0}, 		// * 
	{0, 0, 0}, 		// + 
	{1, 2, 4}, 		// , 
	{0, 0, 0}, 		// - 
	{1, 1, 5}, 		// . 
	{4, 8, 6}, 		// / 
	{4, 6, 10}, 		// 0 
	{3, 6, 14}, 		// 1 
	{4, 6, 17}, 		// 2 
	{4, 6, 21}, 		// 3 
	{5, 6, 25}, 		// 4 
	{4, 6, 30}, 		// 5 
	{4, 6, 34}, 		// 6 
	{4, 6, 38}, 		// 7 
	{4, 6, 42}, 		// 8 
	{4, 6, 46}, 		// 9 
	{1, 5, 50}, 		// : 
	{0, 0, 0}, 		// ; 
	{0, 0, 0}, 		// < 
	{0, 0, 0}, 		// = 
	{0, 0, 0}, 		// > 
	{0, 0, 0}, 		// ? 
	{0, 0, 0}, 		// @ 
	{3, 6, 51}, 		// A 
	{4, 6, 54}, 		// B 
	{4, 6, 58}, 		// C 
	{4, 6, 62}, 		// D 
	{3, 6, 66}, 		// E 
	{3, 6, 69}, 		// F 
	{4, 6, 72}, 		// G 
	{4, 6, 76}, 		// H 
	{1, 6, 80}, 		// I 
	{2, 6, 81}, 		// J 
	{4, 6, 83}, 		// K 
	{3, 6, 87}, 		// L 
	{5, 6, 90}, 		// M 
	{4, 6, 95}, 		// N 
	{4, 6, 99}, 		// O 
	{3, 6, 103}, 		// P 
	{4, 7, 106}, 		// Q 
	{4, 6, 110}, 		// R 
	{4, 6, 114}, 		// S 
	{3, 6, 118}, 		// T 
	{4, 6, 121}, 		// U 
	{3, 6, 125}, 		// V 
	{5, 6, 128}, 		// W 
	{3, 6, 133}, 		// X 
	{5, 6, 136}, 		// Y 
	{3, 6, 141}, 		// Z 
	{0, 0, 0}, 		  // [ 
	{4, 8, 144}, 		// \ .
	{0, 0, 0}, 		  // ] 
	{0, 0, 0}, 		  // ^ 
	{0, 0, 0}, 		  // _ 
	{2, 2, 148}, 		// ` 
	{3, 5, 150}, 		// a 
	{3, 6, 153}, 		// b 
	{3, 5, 156}, 		// c 
	{3, 6, 159}, 		// d 
	{3, 5, 162}, 		// e 
	{2, 6, 165}, 		// f 
	{4, 8, 167}, 		// g 
	{3, 6, 171}, 		// h 
	{1, 7, 174}, 		// i 
	{2, 9, 175}, 		// j 
	{3, 6, 179}, 		// k 
	{1, 6, 182}, 		// l 
	{5, 5, 183}, 		// m 
	{3, 5, 188}, 		// n 
	{3, 5, 191}, 		// o 
	{3, 7, 194}, 		// p 
	{3, 7, 197}, 		// q 
	{3, 5, 200}, 		// r 
	{3, 5, 203}, 		// s 
	{2, 6, 206}, 		// t 
	{3, 5, 208}, 		// u 
	{3, 5, 211}, 		// v 
	{5, 5, 214}, 		// w 
	{3, 5, 219}, 		// x 
	{3, 7, 222}, 		// y 
	{2, 5, 225}, 		// z 
};

// Font information for Franklin Gothic Medium Cond 7pt
const FONT_INFO franklinGothicMediumCond_7ptFontInfo =
{
	12, //  Character height
	' ', //  Start character
	'z', //  End character
  1,  // width of space
	franklinGothicMediumCond_7ptDescriptors, //  Character descriptor array
	franklinGothicMediumCond_7ptBitmaps, //  Character bitmap array
};

